title: Visual Framework Figure
label: Figure

status: beta
context:
  component-type: element

  text: Version, 1982, Adenovirus with 217 dots
  alttext: hello alt text
  imageUrl: "/assets/vf-figure/assets/figure-example.png"
