# Deploy to gh-pages
# https://docs.travis-ci.com/user/deployment-v2/providers/pages/
dist: trusty
language: node_js
node_js:
  - 12

stages:
  - deploy

before_script:
  # - npm install
  - yarn install
  - yarn run build

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN #https://docs.travis-ci.com/user/deployment/pages/
  edge: true # opt in to dpl v2
  fqdn: allaboutken.com
  cleanup: false
  keep_history: false
  target_branch: gh-pages
  local_dir: build
  cache:
    paths:
      - node_modules
  on:
    branch:
      - master
